export const DOCUMENT_OPTIONS = [
  'Marksheet – Semester 1',
  'Marksheet – Semester 2',
  'Marksheet – Semester 3',
  'Marksheet – Semester 4',
  'Marksheet – Semester 5',
  'Marksheet – Semester 6',
  'Marksheet – Semester 7',
  'Marksheet – Semester 8',
  'Marksheet – Semester 9',
  'Marksheet – Semester 10',
  'Consolidated Marksheet',
  'Final Marksheet',
  'Degree Certificate',
  'Provisional Certificate',
  'Migration Certificate',
  'Simple Transcript',
  'WES Transcript',
  'Bonafide Certificate',
  'Course Completion Certificate',
  'Medium of Instruction Certificate',
  'Enrollment Certificate',
  'Registration Certificate',
  'Transfer Certificate',
  'Character Certificate',
  'Duplicate Marksheet',
  'Duplicate Degree',
  'Other Certificate – Custom',
  'Entrance Exam Result',
  'Admission Offer Letter',
  'Admission Confirmation Letter',
  'Guide Allotment Letter',
  'Course Work Completion Certificate',
  'Coursework Marksheet',
  'RDC/DRC Letter',
  'Synopsis Approval Letter',
  'Progress Report Acknowledgement',
  'Pre-Thesis Letter',
  'Thesis Approval Letter',
  'Plagiarism Certificate',
  'Viva Examination Notification',
  'Viva Voce Letter',
  'Provisional & Migration Certificate',
  'PhD Notification',
];
