export const DOCUMENT_OPTIONS = [
  'Marksheet Year One',
  'Marksheet Year Two',
  'Marksheet Year Three',
  'Marksheet Year Four',
  'Marksheet Year Five',
  'Consolidated Marksheet',
  'Final Marksheet',
  'Degree Certificate',
  'Provisional Certificate',
  'Migration Certificate',
  'Simple Transcript',
  'WES Transcript',
  'Bonafide Certificate',
  'Course Completion Certificate',
  'Medium of Instruction Certificate',
  'Enrollment Certificate',
  'Registration Certificate',
  'Transfer Certificate',
  'Character Certificate',
  'Duplicate Marksheet',
  'Duplicate Degree',
  'Other Certificate - Custom',
  'Entrance Exam Result',
  'Admission Offer Letter',
  'Admission Confirmation Letter',
  'Guide Allotment Letter',
  'Course Work Completion Certificate',
  'Coursework Marksheet',
  'RDC/DRC Letter',
  'Synopsis Approval Letter',
  'Progress Report Acknowledgement',
  'Pre-Thesis Letter',
  'Thesis Approval Letter',
  'Plagiarism Certificate',
  'Viva Examination Notification',
  'Viva Voce Letter',
  'Provisional & Migration Certificate',
  'PhD Notification',
];
